Blockchain view
ctisbtes/btes pull request #63
Opened 2021-02-23 17:29 UTC by sukrukirman

Positon update log bug and blockchain data tree added.
Olmayan bi yer varsa söyleyin, ben hallederim, siz uğraşmayın. Yanlış anladığım veya yanlış yaptığım şeyler olmuş olabilir.

2021-02-23 18:40 UTC, starikcetin requested changes
Şükrü çok geriden başlayıp hiç rebase/merge yapmadan ilerlemişsin, eğer halledebileceğini düşünüyorsan yazdıklarımı düzelt, conflictleri çöz, sonra tekrar bi review daha yapayım. Eğer çok karmaşık gelecekse haber ver, beraber bakalım.

2021-02-23 18:40 UTC, starikcetin commented on common/src/SimulationSnapshot.ts
> +import { BlockchainData } from 'frontend/src/state/simulation/BlockchainData';
`common` package'ı kendisi hariç diğer hiçbir package'dan import yapamaz! Eğer yanlışlık olmadıysa ve gerçekten böyle bir import yapman gerekiyorsa `BlockchainData`yı da `common` package'ına taşı.

2021-02-23 18:40 UTC, starikcetin commented on common/src/SimulationSnapshot.ts
> +  readonly blockchainData: BlockchainData;
Tahminimce burada type olarak `BlockchainData` değil `SimulationBlockchainDataSnapshot` kullanman gerekiyor

2021-02-23 18:40 UTC, starikcetin commented on frontend/src/components/BlockchainTreeView/BlockchainTreeView.tsx
> +}
Bu interface `BlockchainData`nın aynısı. İkisinden birini silelim.

Not: İsmin `BlockchainBlock` olması bana daha mantıklı geliyor.

2021-02-23 18:40 UTC, starikcetin commented on frontend/src/components/BlockchainTreeView/BlockchainTreeView.tsx
> +function format(rootBlock: BlockchainBlock, isRoot = true): TreeNode {
`TreeNode`u elle tanımlamak yerine kütüphanenin kendi type'ını kullanmak daha sağlıklı:

```ts
import { RawNodeDatum } from 'react-d3-tree/lib/types/common';
```

https://github.com/bkrem/react-d3-tree#providing-data

2021-02-23 18:40 UTC, starikcetin commented on frontend/src/components/SimulationNode/SimulationNode.tsx
> +    //Send new position of the node
Çift tıklama sırasında ufacık bir pozisyon değşimi olması bile yine eski davranışa neden olur. Quire task'ına yazdığım gibi ya `grid` seçeneği ile çözülmesi gerekiyordu, ya da drag için minimum bir threshold belirleyip mesafe ölçümü yapman gerekliydi.

Ama bunu şimdilik kabul edelim, tekrar uğraşacak vaktimiz yok. Sonradan boşluk olursa geri dönülebilir.

2021-02-23 18:40 UTC, starikcetin commented on frontend/src/state/simulation/SimulationBlockchainDataPayload.ts
> +export interface SimulationBlockchainDataPayload {
İsim: `SimulationBlockchainDataActionPayload` 
`Action`ı unutmuşsun.

2021-02-23 18:40 UTC, starikcetin commented on frontend/src/state/simulation/simulationSlice.ts
> +        blockchainData: { hash: '', children: [] },
`null` daha uygun bir default değer. View'da gösterim yaparken de null ise `No blockchain data received yet` gibi bir mesaj gösterilebilir.

2021-02-23 18:40 UTC, starikcetin commented on frontend/src/state/simulation/simulationSlice.ts
> +    },
Bu action sanırım kullanılmıyor. Silelim, sonradan kafamızı karıştırmasın.

2021-02-23 18:40 UTC, starikcetin commented on backend/src/core/Simulation.ts
> +  };
`Simulation`ın `Blockchain`i olamaz, `SimulationNode`un olabilir.

2021-02-25 11:14 UTC, sukrukirman commented
> Şükrü çok geriden başlayıp hiç rebase/merge yapmadan ilerlemişsin, eğer halledebileceğini düşünüyorsan yazdıklarımı düzelt, conflictleri çöz, sonra tekrar bi review daha yapayım. Eğer çok karmaşık gelecekse haber ver, beraber bakalım.

Çok fazla değişiklik yapmam gerekiyor, merge ile uğraşmak yerine yeni branch açıp değişikleri güncelleyip oraya taşıyacağım.

2021-02-25 13:43 UTC, starikcetin commented
> > Şükrü çok geriden başlayıp hiç rebase/merge yapmadan ilerlemişsin, eğer halledebileceğini düşünüyorsan yazdıklarımı düzelt, conflictleri çöz, sonra tekrar bi review daha yapayım. Eğer çok karmaşık gelecekse haber ver, beraber bakalım.
> 
> Çok fazla değişiklik yapmam gerekiyor, merge ile uğraşmak yerine yeni branch açıp değişikleri güncelleyip oraya taşıyacağım.

Ok bu PR'ı sen kapatırsın yenisini açınca.

2021-02-26 06:50 UTC, starikcetin commented
Superseded by: https://github.com/ctisbtes/btes/pull/68

2021-02-26 06:50 UTC, closed without merging

2021-02-26 09:22 UTC, starikcetin commented
This branch is renamed and archived. The new branch name is `archive/blockchain-view-v1`.